### PR TITLE
Fix/fix appveyer build for 8.0

### PR DESCRIPTION
**Pull request by nick-zh**

### CODE REVIEW

**Comment by nick-zh** [comment]
@cmb69 Heya, i am preparing my ci for 8.1 since the archive is already present. Somehow the appveyor build for 8.0 fails (with or without the visual studio image), what am i missing here? Sry about pinging you, but i have not enough insight how the build exaclty works :sweat:

**Comment by nick-zh** [comment]
On a sidenote, would it be feasible to update librdkafka to at least 1.6.0? 1.5.3 is now almost a year old and a lot of fixes have been introduced in 1.6.x :smile:

**Comment by cmb69** [comment]
Yeah, that error message isn't particularly helpful. I'm going to debug.

I'll see what I can do regarding updating librdkafka to 1.6.

**Comment by nick-zh** [comment]
Awesome, as always, many many thanks for your quick help and response :bow: :pray:

**Comment by cmb69** [comment]
Okay, this PR is certainly wrong; PHP 8.0 is supposed to be build with Visual Studio 2019 (aka. vs16). I did a respective build in my fork, and [that succeeded](https://ci.appveyor.com/project/cmb69/php-simple-kafka-client/builds/41664401). I suggest to re-run https://ci.appveyor.com/project/nick-zh/php-simple-kafka-client/builds/41664001; that download failure might have been just a temporary issue.

**Comment by nick-zh** [comment]
Thx for the fast feedback, i'll re-run the build on the original branch and check again :pray:

**Comment by nick-zh** [comment]
I had vc15 by mistake instead of vs16 for php8.0, must have happened during the adjustments. Many thanks and sry for the inconvenience :disappointed:

**Comment by cmb69** [comment]
No problem. :)

**Pull request closed without merging**
